Vistoria/Models/Modulo.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vistoria.Models
{
    [Serializable]
    public class Modulo : AbstractModel
    {
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Informe o {0}")]
        public string Nome { get; set; }

        [Display(Name = "Path")]
        [Required(ErrorMessage = "Informe o {0}")]
        public string Path { get; set; }

        [JsonIgnore]
        public virtual ICollection<Grupo> ListGrupo { get; set; }

        [Display(Name = "Grupos de Acesso")]
        [NotMapped]
        public List<long> GruposId { get; set; }
    }
}

Vistoria/Controllers/ModuloController.cs
using Vistoria.Models;
using Vistoria.Models.Context;
using Vistoria.Business;
using Vistoria.Enumerators;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using static Vistoria.Business.Utils;

namespace Vistoria.Controllers
{
    public class ModuloController : AbstractController<VistoriaContext>
    {
        // GET: Modulos
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [OutputCache(Duration = 0)]
        public virtual ActionResult Pagination(string sEcho, int iDisplayStart, int iColumns, int iDisplayLength, string sSearch, int iSortCol_0, string sSortDir_0)
        {
            string controller = ControllerContext.RouteData.Values["Controller"].ToString();
            sSearch = $"%{sSearch}%";
            var query = db.Modulo.Ativos().Where(x => DbFunctions.Like(x.Nome, sSearch));
            if (sSortDir_0.ToLower() == "asc")
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderBy(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderBy(x => x.Nome);
                        break;
                    case 2:
                        query = query.OrderBy(x => x.Path);
                        break;
                }
            }
            else
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderByDescending(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderByDescending(x => x.Nome);
                        break;
                    case 2:
                        query = query.OrderByDescending(x => x.Path);
                        break;
                }
            }
            int recordsTotal = query.Count();
            var aList = query.Skip(iDisplayStart).Take(iDisplayLength);
            var data = aList.ToList().Select(x => new
            {
                x.Id,
                x.Nome,
                x.Path,
                acoes = $"<a href='{Url.Action("Edit", controller)}/{x.Id}'><i class='glyphicon glyphicon-pencil'></i> Editar</a><button class='btn-link' onClick=\"excluir('{controller}', {x.Id}, '{x.Nome}')\"><i class='glyphicon glyphicon-trash'></i> Excluir</button>"
            }).ToArray();
            return Json(new
            {
                iDraw = 1,
                sEcho,
                iTotalRecords = recordsTotal,
                iTotalDisplayRecords = recordsTotal,
                aaData = data
            }, JsonRequestBehavior.AllowGet);
        }

        // GET: Modulos/Edit/5
        public ActionResult Edit(long? id)
        {
            Modulo modulo = new Modulo();
            ViewBag.Grupos = db.Grupo
                .Ativos()
                .OrderBy(x => x.Nome)
                .ToList();
            ViewBag.GruposChecked = new List<Grupo>();
            if (id != null)
            {
                modulo = db.Modulo.Find(id);
                ViewBag.GruposChecked = db.Modulo.Find(id).ListGrupo.ToList();
            }
            var selectListItems = new List<SelectListItem>();
            return View(modulo);
        }

        // POST: Modulos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Modulo _modulo)
        {
            bool inserir = _modulo.Id == 0;
            try
            {
                db.Database.BeginTransaction(IsolationLevel.ReadUncommitted);
                if (inserir)
                {
                    _modulo.ListGrupo = new List<Grupo>();
                    db.Modulo.Add(_modulo);
                }
                else
                {
                    Modulo banco = db.Modulo.Find(_modulo.Id);
                    banco.Nome = _modulo.Nome;
                    banco.Path = _modulo.Path;
                    banco.GruposId = _modulo.GruposId;
                    _modulo = banco;
                }
                db.SaveChanges();

                _modulo.ListGrupo.Clear();
                _modulo.GruposId.ForEach(x =>
                   _modulo.ListGrupo.Add(db.Grupo.Find(x))
                );

                db.SaveChanges();
                db.Database.CurrentTransaction.Commit();
                SessionHelper.AddMessage(MessageTipo.Success, "Cadastro de Módulo", "Módulo "+ (inserir ? "Inserido":"Alterado") + " com sucesso");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                db.Database.CurrentTransaction.Rollback();
                SessionHelper.AddMessage(MessageTipo.Danger, "Cadastro de Módulo", "Ocorreu um erro ao salvar o Módulo: " + e.Message);

                ViewBag.Grupos = db.Grupo
                    .Ativos()
                    .OrderBy(x => x.Nome)
                    .ToList();
                ViewBag.GruposChecked = new List<Grupo>();
                if (!inserir)
                {
                    ViewBag.GruposChecked = db.Modulo.Find(_modulo.Id).ListGrupo.ToList();
                }
                return View(_modulo);
            }
        }

        public ActionResult Delete(int id)
        {
            Modulo modulo = db.Modulo.Find(id);
            db.Modulo.Remove(modulo);
            db.SaveChanges();
            SessionHelper.AddMessage(MessageTipo.Success, "Cadastro de Módulo", "Módulo excluído com sucesso");
            return RedirectToAction("Index");
        }

    }
}

Vistoria/Views/Modulo/Edit.cshtml
@model Vistoria.Models.Modulo
@{
    ViewBag.Title = "Módulo";
    List<Vistoria.Models.Grupo> listaGrupos = ViewBag.GruposChecked;
    ViewBag.Tamanho = 2;
}
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Cadastro de Módulo</h3>
        </div>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "formId", @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.AntiForgeryToken()
            HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
            @Html.HiddenFor(model => model.Id)

            <div class="box-body">
                <div class="form-group">
                    @Html.LabelFor(m => m.Nome, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Path, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Path, new { @class = "form-control", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.Path, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.GruposId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @foreach (Vistoria.Models.Grupo grupo in ViewBag.Grupos)
                        {
                            <div class="col-sm-12 no-pdd">
                                <label><input type="checkbox" class="minimal" @(listaGrupos.Where(x => x.Id == grupo.Id).Count() > 0 ? "checked=checked" : "") name="GruposId" value="@grupo.Id" />@grupo.Nome</label>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="form-group no-mrg-btm">
                    <div class="col-md-offset-2 col-xs-6 col-sm-6 col-md-4 col-lg-2">
                        <button type="submit" class="btn btn-primary btn-block"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-2">
                        <a class="btn btn-default btn-block" href="@Url.Action("Index", "Modulo")"><i class="glyphicon glyphicon glyphicon glyphicon-arrow-left"></i> Voltar</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts {
    <script>
        validator.rules = {
            'Nome': {
                required: true
            },
            'Path': {
                required: true
            },
            'GruposId': {
                required: true,
            }
        };
        validator.messages = {
            'Nome': 'Informe o Nome',
            'Path': 'Informe o Path',
            'GruposId': 'Informe pelo menos um Grupo'
        };

        $(document).ready(function () {
            $('#formId').validate(validator);
        });
    </script>
}

Vistoria/Views/Modulo/Index.cshtml
@{
    ViewBag.Title = "Módulo";
    ViewBag.Tamanho = 2;
}
@section botaoTop {
    <a href="@Url.Action("Edit", "Modulo")" class="btn btn-primary" style="float:right"><i class="glyphicon glyphicon-plus"></i> Novo Módulo</a>
}
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listagem de Módulo</h3>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-striped datatable tipo1">
                <thead>
                    <tr>
                        <th width="30">#</th>
                        <th>Nome</th>
                        <th>Path</th>
                        <th width="200">Ações</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
    @section Scripts {
        <script>
    $(document).ready(function () {
        $('.datatable.tipo1').DataTable({
            'bPaginate': true,
            'bJQueryUI': true,
            'bProcessing': true,
            'bServerSide': true,
            'sAjaxSource': '@Url.Action("Pagination", "Modulo")',
            'sServerMethod': 'POST',
            'columnDefs': [
                { 'orderable': false, "targets": 3 }
            ],
            'aoColumns': [
                { 'mData': 'Id' },
                { 'mData': 'Nome' },
                { 'mData': 'Path' },
                { 'mData': 'acoes' }
            ],
            'language': {
                'url': '@Vistoria.Business.Utils.FullUrl' + 'Content/js/datatables.net/pt-BR.json'
            }
        });
    });
        </script>
    }