Vistoria/Models/Usuario.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vistoria.Models
{
    public class Usuario : AbstractModel
    {
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Informe o {0}")]
        public string Nome { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Informe o {0}")]
        public string Email { get; set; }

        [Display(Name = "Login")]
        [Required(ErrorMessage = "Informe o {0}")]
        public string Login { get; set; }

        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [Display(Name = "Matrícula do Atendente")]
        [Required(ErrorMessage = "Informe a {0}")]
        public long MatriculaAtendente { get; set; }

        [Display(Name = "Autenticação no AD?")]
        [Required(ErrorMessage = "Informe {0}")]
        public bool AutenticaAD { get; set; }

        public string Token { get; set; }

        public string Biometria { get; set; }
        public string TokenBiometria { get; set; }
        public string HashBiometria { get; set; }

        [Display(Name = "Sitio")]
        [ForeignKey("Sitio")]
        public long SitioId { get; set; }

        public virtual Sitio Sitio { get; set; }

        public virtual List<Grupo> ListGrupo { get; set; }

        [JsonIgnore]
        [NotMapped]
        public List<Modulo> ListModulo;

        [Display(Name = "Grupos de Acesso")]
        [NotMapped]
        public List<int> GruposId { get; set; }
    }
}

Vistoria/Controllers/UsuarioController.cs
using Vistoria.Business;
using Vistoria.Enumerators;
using Vistoria.Models;
using Vistoria.Models.Context;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Security;

namespace Vistoria.Controllers
{
    public class UsuarioController : AbstractController<VistoriaContext>
    {
        // GET: Usuarios
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [OutputCache(Duration = 0)]
        public virtual ActionResult Pagination(string sEcho, int iDisplayStart, int iColumns, int iDisplayLength, string sSearch, int iSortCol_0, string sSortDir_0)
        {
            string controller = ControllerContext.RouteData.Values["Controller"].ToString();
            sSearch = $"%{sSearch}%";
            var query = db.Usuario.Ativos().Where(x => DbFunctions.Like(x.Nome.ToLower(), sSearch.ToLower()) || 
                                                       DbFunctions.Like(x.Login.ToLower(), sSearch.ToLower()) ||
                                                       DbFunctions.Like(x.Email.ToLower(), sSearch.ToLower()) ||
                                                       DbFunctions.Like(x.MatriculaAtendente.ToString(), sSearch.ToLower()));
            if (sSortDir_0.ToLower() == "asc")
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderBy(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderBy(x => x.Nome);
                        break;
                    case 2:
                        query = query.OrderBy(x => x.Login);
                        break;
                    case 3:
                        query = query.OrderBy(x => x.Email);
                        break;
                    case 4:
                        query = query.OrderBy(x => x.MatriculaAtendente);
                        break;
                }
            }
            else
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderByDescending(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderByDescending(x => x.Nome);
                        break;
                    case 2:
                        query = query.OrderByDescending(x => x.Login);
                        break;
                    case 3:
                        query = query.OrderByDescending(x => x.Email);
                        break;
                    case 4:
                        query = query.OrderByDescending(x => x.MatriculaAtendente);
                        break;
                }
            }
            int recordsTotal = query.Count();
            var aList = query.Skip(iDisplayStart).Take(iDisplayLength);
            var data = aList.ToList().Select(x => new
            {
                x.Id,
                x.Nome,
                x.Login,
                x.Email,
                x.MatriculaAtendente,
                acoes = $"<a href='{Url.Action("Edit", controller)}/{x.Id}'><i class='glyphicon glyphicon-pencil'></i> Editar</a><button class='btn-link' onClick=\"excluir('{controller}', {x.Id}, '{x.Nome}')\"><i class='glyphicon glyphicon-trash'></i> Excluir</button>"
            }).ToArray();
            return Json(new
            {
                iDraw = 1,
                sEcho,
                iTotalRecords = recordsTotal,
                iTotalDisplayRecords = recordsTotal,
                aaData = data
            }, JsonRequestBehavior.AllowGet);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(long? id)
        {
            Usuario usuario = new Usuario();
            ViewBag.Grupos = db.Grupo
                .Ativos()
                .OrderBy(x => x.Nome)
                .ToList();
            ViewBag.GruposChecked = new List<Grupo>();
            if (id != null)
            {
                usuario = db.Usuario.Find(id);
                ViewBag.GruposChecked = db.Usuario.Find(usuario.Id).ListGrupo.ToList();
                ViewBag.SitioId = new SelectList(db.Sitio.Ativos().OrderBy(x => x.Nome), "Id", "Nome", usuario?.SitioId);
            }
            else
            {
                ViewBag.SitioId = new SelectList(db.Sitio.Ativos().OrderBy(x => x.Nome), "Id", "Nome");
            }
            usuario.Senha = string.Empty;
            var selectListItems = new List<SelectListItem>();
            return View(usuario);
        }

        public string  ResetSenha()
        {
            return Membership.GeneratePassword(8, 4);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario _usuario)
        {
            bool inserir = _usuario.Id == 0;
            try
            {

                var dic = new Dictionary<string, string>();
                dic.Add("{#Login}", _usuario.Login);
                string html;
                if (_usuario.AutenticaAD == false)
                {
                    if(string.IsNullOrEmpty(_usuario.Senha) && inserir == true)
                    {
                        SessionHelper.AddMessage(MessageTipo.Danger, "Cadastro de Usuário", "Campo Senha é Obrigatório");
                    }

                    dic.Add("{#Senha}", _usuario.Senha);
                    html = Utils.LerTemplateEsubstituirTags(Server.MapPath("~/Templates/usuarioSenha.html"), dic);
                }
                else
                {
                    html = Utils.LerTemplateEsubstituirTags(Server.MapPath("~/Templates/usuario.html"), dic);
                }

                db.Database.BeginTransaction(IsolationLevel.ReadUncommitted);
                if (inserir)
                {
                    UsuarioBO.Inserir(db, _usuario);

                    var task = Task.Factory
                        .StartNew(() =>
                        {
                            try
                            {
                               SendEmail.Enviar(_usuario.Email, "Acesso ao sistema", html);
                            }
                            catch(Exception)
                            {
                            }
                            
                        }); 
                }
                else
                {
                    UsuarioBO.Alterar(db, _usuario);
                }
                db.SaveChanges();
                db.Database.CurrentTransaction.Commit();
                SessionHelper.AddMessage(MessageTipo.Success, "Cadastro de Usuário", "Usuário " + (inserir ? "Inserido" : "Alterado") + " com sucesso");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                db.Database.CurrentTransaction.Rollback();
                SessionHelper.AddMessage(MessageTipo.Danger, "Cadastro de Usuário", "Ocorreu um erro ao salvar o Usuário: " + e.Message);

                ViewBag.Grupos = db.Grupo
                    .Ativos()
                    .OrderBy(x => x.Nome)
                    .ToList();
                ViewBag.GruposChecked = new List<Grupo>();
                if (!inserir)
                {
                    ViewBag.GruposChecked = db.Usuario.Find(_usuario.Id).ListGrupo.ToList();
                }

                return View(_usuario);
            }
        }

        public ActionResult Delete(int id)
        {
            Usuario usuario = db.Usuario.Find(id);
            db.Usuario.Remove(usuario);
            db.SaveChanges();
            SessionHelper.AddMessage(MessageTipo.Success, "Cadastro de Usuário", "Usuário excluído com sucesso");
            return RedirectToAction("Index");
        }

    }
}

Vistoria/Views/Usuario/Edit.cshtml
@model Vistoria.Models.Usuario
@{
    ViewBag.Title = "Usuário";
    List<Vistoria.Models.Grupo> listaGrupos = ViewBag.GruposChecked;
    ViewBag.Tamanho = 2;
}
<div class="col-xs-12">
    <div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de Usuário</h3>
    </div>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "formId", @class = "form-horizontal", role = "form" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        @Html.HiddenFor(model => model.Id)

        <div class="box-body">
            <div class="form-group">
                @Html.LabelFor(model => model.AutenticaAD, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    <div class="checkbox">
                        <input type="checkbox" class="minimal" name="AutenticaAD" id="AutenticaAD" value="true" @(Model.AutenticaAD == true ? "checked=checked" : "") />
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Nome, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Login, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Login, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.MatriculaAtendente, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.MatriculaAtendente, new { @class = "form-control", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.MatriculaAtendente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SitioId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SitioId", null, Vistoria.Business.Utils.txtSelecioneCombos, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SitioId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group div-senha @(Model.AutenticaAD == true ? "hide" : "")">
                @Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m.Senha, new { @class = "form-control",@id= "Senha" })
                    @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                </div>
                
                <div class="col-md-2">
                    <button type="button" class="btn btn-primary btn-block" onclick="gerarSenha()"><i></i> Gerar Senha</button>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.GruposId, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @foreach (Vistoria.Models.Grupo grupo in ViewBag.Grupos)
                    {
                        <div class="col-sm-12 no-pdd">
                            <label><input type="checkbox" class="minimal" @(listaGrupos.Where(x => x.Id == grupo.Id).Count() > 0 ? "checked=checked" : "") name="GruposId" value="@grupo.Id" />  @grupo.Nome</label>
                        </div>
                    }
                    @Html.ValidationMessageFor(m => m.GruposId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Biometria, "Biometria Cadastrada?", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (String.IsNullOrEmpty(Model.Biometria))
                    {
                        <small class="label bg-danger">Não</small>
                    }
                    else
                    {
                        <small class="label bg-green">Sim</small>
                    }
                    <a class="btn btn-primary mrg-left-20" onclick="Capture()"><img style="width: 16px; height: 16px;" src="@(Vistoria.Business.Utils.FullUrl)Content/img/digital.svg">&nbsp;Cadastrar</a>
                </div>
            </div>

        </div>
        <div class="box-footer">
            <div class="form-group no-mrg-btm">
                <div class="col-md-offset-2 col-xs-6 col-sm-6 col-md-4 col-lg-2">
                    <button type="submit" class="btn btn-primary btn-block"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-2">
                    <a class="btn btn-default btn-block" href="@Url.Action("Index", "Usuario")"><i class="glyphicon glyphicon glyphicon glyphicon-arrow-left"></i> Voltar</a>
                </div>
            </div>
        </div>
    }
    </div>
</div>

<style>
    .bg-danger {
        background-color: #dd4b39 !important;
    }
</style>

@section Scripts {
    <script>
        validator.rules = {
            'Nome': {
                required: true
            },
            'Login': {
                required: true
            },
            'Email': {
                required: true
            },
            'MatriculaAtendente': {
                required: true
            },
            'GrupoId': {
                required: true
            },
            'GruposId': {
                required: true,
            }
        };
        validator.messages = {
            'Nome': 'Informe o Nome',
            'Login': 'Informe o Login',
            'Email': 'Informe o E-mail',
            'MatriculaAtendente': 'Informe a Matrícula',
            'GrupoId': 'Informe o Grupo',
            'GruposId': 'Informe pelo menos um Grupo de Acesso',
        };

        $(document).ready(function () {
            $('#formId').validate(validator);

            $(".iCheck-helper:first").click(function () {
                if ($("#AutenticaAD").is(":checked") == true) {
                    $(".div-senha").addClass("hide");
                } else {
                    $(".div-senha").removeClass("hide");
                }
            });
        });


        function Capture() {
            $.ajax({
                url: '@System.Configuration.ConfigurationManager.AppSettings["URL_SERVICO_BIOMETRIA"]api/public/v1/captura/Capturar/1',
                type: 'GET',
                success: function (data) {
                    if (data != "" && data != null) {
                        insertDB(data);
                    }
                    else {
                        alert("Digital não pode ser capturada!");
                    }
                }
            })
        }

        function insertDB(template) {
            $.ajax({
                method: "POST",
                dataType: 'json',
                url: "@Url.Action("Cadastrar", "api/Biometria")",
                data: {
                    id: $("#Id").val(),
                    template: template
                },
            }).done(function (result) {
                alert(result.Mensagem);

            }).fail(function (jqXHR, textStatus) {
                alert("Request failed: " + textStatus);
            });
        }


        function gerarSenha() {
            var lower = 'abcdefghijklmnopqrstuvwxyz'.split('');
            var upper = 'abcdefghijklmnopqrstuvwxyz'.toUpperCase().split('');
            var nuns = '0123456789'.split('');
            var senha = "";
            for (i = 0; i < 3; i++) {
                var x = (Math.random() * lower.length);
                senha += lower[parseInt(x)];
            }
            for (i = 0; i < 2; i++) {
                var x = (Math.random() * nuns.length);
                senha += nuns[parseInt(x)];
            }
            for (i = 0; i < 3; i++) {
                var x = (Math.random() * upper.length);
                senha += upper[parseInt(x)];
            }

            $('#Senha').val(senha);

        }


        function gerarSenhaAjax() {
            $.get('@Url.Action("ResetSenha","Usuario")', function (result) {
                $("#Senha").val(result);
            });
        }




    </script>
}

Vistoria/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Usuário";
    ViewBag.Tamanho = 2;
}
@section botaoTop {
    <a href="@Url.Action("Edit", "Usuario")" class="btn btn-primary" style="float:right"><i class="glyphicon glyphicon-plus"></i> Novo Usuário</a>
}
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listagem de Usuário</h3>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-striped datatable tipo1">
                <thead>
                    <tr>
                        <th width="30">#</th>
                        <th>Nome</th>
                        <th>Login</th>
                        <th>Email</th>
                        <th>Matrícula</th>
                        <th width="200">Ações</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('.datatable.tipo1').DataTable({
                'bPaginate': true,
                'bJQueryUI': true,
                'bProcessing': true,
                'bServerSide': true,
                'sAjaxSource': '@Url.Action("Pagination", "Usuario")',
                'sServerMethod': 'POST',
                'columnDefs': [
                    { 'orderable': false, "targets": 5 }
                ],
                'aoColumns': [
                    { 'mData': 'Id' },
                    { 'mData': 'Nome' },
                    { 'mData': 'Login' },
                    { 'mData': 'Email' },
                    { 'mData': 'MatriculaAtendente' },
                    { 'mData': 'acoes' }
                ],
                'language': {
                    'url': '@Vistoria.Business.Utils.FullUrl' + 'Content/js/datatables.net/pt-BR.json'
                }
            });
        });
    </script>
}