Vistoria/Models/LogErro.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vistoria.Models
{
    public class LogErro
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        [Display(Name = "Ação")]
        public string Acao { get; set; }
        public string StackTrace { get; set; }
        public string Message { get; set; }
        public string ContentApiString { get; set; }
        public DateTime Data { get; set; }
        
    }
}

Vistoria/Controllers/LogErroController.cs
using Vistoria.Business;
using Vistoria.Controllers;
using Vistoria.Enumerators;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vistoria.Models;
using Vistoria.Models.Context;

namespace Vistoria.Controllers
{
    public class LogErroController : AbstractController<VistoriaContext>
    {

        public ActionResult Index()
        {
			return View();
        }

		[HttpPost]
        public virtual ActionResult Pagination(string sEcho, int iDisplayStart, int iColumns, int iDisplayLength, string sSearch, int iSortCol_0, string sSortDir_0)
        {
            sSearch = $"%{sSearch}%";
            var query = db.LogErro.Where(x => DbFunctions.Like(x.Acao, sSearch)).OrderByDescending(x => x.Data);
            if (sSortDir_0.ToLower() == "asc")
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderBy(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderBy(x => x.Acao);
                        break;
                    case 2:
                        query = query.OrderBy(x => x.StackTrace);
                        break;
                    case 3:
                        query = query.OrderBy(x => x.Message);
                        break;
                    case 4:
                        query = query.OrderBy(x => x.ContentApiString);
                        break;
                    case 5:
                        query = query.OrderBy(x => x.Data);
                        break;
                }
            }
            else
            {
                switch (iSortCol_0)
                {
                    case 0:
                        query = query.OrderByDescending(x => x.Id);
                        break;
                    case 1:
                        query = query.OrderByDescending(x => x.Acao);
                        break;
                    case 2:
                        query = query.OrderByDescending(x => x.StackTrace);
                        break;
                    case 3:
                        query = query.OrderByDescending(x => x.Message);
                        break;
                    case 4:
                        query = query.OrderByDescending(x => x.ContentApiString);
                        break;
                    case 5:
                        query = query.OrderByDescending(x => x.Data);
                        break;
                }
            }

            int recordsTotal = query.Count();
            var aList = query.Skip(iDisplayStart).Take(iDisplayLength);
            var data = aList.ToList().Select(x => new
            {
				x.Id,
				x.Acao,
				x.StackTrace,
				x.Message,
				x.ContentApiString,
                DataHora = x.Data.ToString("dd/MM/yyyy HH:mm:ss"),
            }).ToArray();
            return Json(new
            {
                iDraw = 1,
                sEcho,
                iTotalRecords = recordsTotal,
                iTotalDisplayRecords = recordsTotal,
                aaData = data
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

Vistoria/Views/LogErro/Index.cshtml
@model Vistoria.Models.LogErro

@{
    ViewBag.Title = "Log de Erros";
	ViewBag.Tamanho = 2;
}

<style>
    .datatable td {
        white-space: normal !important;
    }
</style>
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Log de Erros</h3>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-striped datatable tipo1">
                <thead>
                    <tr>
                        <th width="30">#</th>
						<th width="200">@Html.LabelFor(model => model.Acao)</th>
						<th width="200">@Html.LabelFor(model => model.StackTrace)</th>
						<th width="200">@Html.LabelFor(model => model.Message)</th>
						<th width="200">@Html.LabelFor(model => model.ContentApiString)</th>
						<th width="200">@Html.LabelFor(model => model.Data)</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts {
    <script>
        $(document).ready(function () {
            $('.datatable.tipo1').DataTable({
                'bPaginate': true,
                'bJQueryUI': true,
                'bProcessing': true,
                'bServerSide': true,
                'sAjaxSource': '@Url.Action("Pagination", "LogErro")',
                'sServerMethod': 'POST',
                "scrollX": true,
                'columnDefs': [
                    { 'orderable': false, "targets": 4 }
                ],
                'aoColumns': [
					{ 'mData': 'Id' },
					{ 'mData': 'Acao' },
					{ 'mData': 'StackTrace' },
					{ 'mData': 'Message' },
					{ 'mData': 'ContentApiString' },
					{ 'mData': 'DataHora' },
                ],
                'language': {
                    'url': '@(Vistoria.Business.Utils.FullUrl)Content/js/datatables.net/pt-BR.json'
                }
            });
        });
    </script>
}