Vistoria/Models/AlterarSenha.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vistoria.Models
{
    [Serializable]
    public class AlterarSenha
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        public string codigoOperacao { get; set; }
        public string novaSenha { get; set; }
        public string senhaConfirmada { get; set; }
        public int codigoRetExec { get; set; }

    }
}

Vistoria/Controllers/SegurancaController.cs
using Vistoria.Business;
using Vistoria.Models;
using Vistoria.Models.Context;
using Vistoria.Models.ViewModel;
using Vistoria.Enumerators;
using System;
using System.Configuration;
using System.Web.Mvc;
using System.Web.Security;

namespace Vistoria.Controllers
{
    public class SegurancaController : AbstractController<VistoriaContext>
    {
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login(string returnUrl)
        {
            if (Request.IsAuthenticated && !string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Usuario model, string returnUrl)
        {
            try
            {
                SegurancaBO.Autenticar(db, model, false);
                
                FormsAuthentication.SetAuthCookie(model.Login, false);

                if (AcessoBO.TemAcesso("Vistoria", "Home", "Index"))
                {
                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return Redirect(ConfigurationManager.AppSettings["URL_DEFAULT"]);
                    }
                }
                else
                {
                    return Redirect("~/Home/Index");
                }

            }
            catch (Exception ex)
            {
                SessionHelper.AddMessage(MessageTipo.Danger, "Erro de autenticação", ex.Message);
                ViewBag.ReturnUrl = returnUrl;
                return View(model);
            }
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);

            filterContext.ExceptionHandled = true;

            var returnUrl = Request["ReturnUrl"];

            if (!string.IsNullOrEmpty(returnUrl))
            {
                filterContext.Result = new RedirectResult(returnUrl);
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Logout(string returnUrl)
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login", new { returnUrl });
        }

        public ActionResult AlterarSenha(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarSenha(AlterarSenhaVM model, string returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ViewBag.ReturnUrl = returnUrl;
                    SegurancaBO.AlterarSenha(db, model);
                    SessionHelper.AddMessage(MessageTipo.Success, "Alterar Senha", "Senha atualiza com sucesso!");
                    return RedirectToAction("AlterarSenha");
                }
            }
            catch(Exception e)
            {
                SessionHelper.AddMessage(MessageTipo.Danger, "Alterar Senha", e.Message);
            }
            return View(model);
        }

    }
}

Vistoria/Views/Seguranca/AlterarSenha.cshtml
@model Vistoria.Models.ViewModel.AlterarSenhaVM
@{
    ViewBag.Title = "Alterar Senha";

    ViewBag.Tamanho = 4;
}
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Alterar Senha</h3>
        </div>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "formId", @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.AntiForgeryToken()
            HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

            <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
            <div class="box-body">
                <div class="form-group">
                    @Html.LabelFor(m => m.SenhaAtual, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.SenhaAtual, new { @class = "form-control", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.SenhaAtual, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.NovaSenha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.NovaSenha, new { @class = "form-control", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.NovaSenha, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmarSenha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.ConfirmarSenha, new { @class = "form-control", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.ConfirmarSenha, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="form-group no-mrg-btm">
                    <div class="col-md-offset-2 col-xs-6 col-sm-6 col-md-4 col-lg-2">
                        <button type="submit" class="btn btn-primary btn-block"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    <script>
        validator.rules = {
            'SenhaAtual': {
                required: true
            },
            'NovaSenha': {
                required: true,
                minlength: 8
            },
            'ConfirmarSenha': {
                required: true,
                minlength: 8,
                equalTo: "#NovaSenha"
            }
        };
        validator.messages = {
            'SenhaAtual': 'Informe a Senha Atual',
            'NovaSenha': {
                required: 'Informe a Nova Senha',
                minlength: 'Mínimo de 8 caracteres'
            },
            'ConfirmarSenha': {
                required: 'Confirme a Nova Senha',
                minlength: 'Mínimo de 8 caracteres',
                equalTo: 'As senhas não conferem'
            }
        };

        $(document).ready(function () {
            $('#formId').validate(validator);
        });
    </script>
}

Vistoria/Views/Seguranca/Login.cshtml
@model Vistoria.Models.Usuario

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@foreach (Vistoria.Models.ViewModel.MessageVM message in Vistoria.Business.SessionHelper.ListMessage)
{
    <div class="alert alert-@(message.MessageTipo.ToString().ToLower()) alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa @(message.GetIcon())"></i> @(message.Titulo)</h4>
        <i class="close icon"></i>
        <p>
            @(message.Texto)
        </p>
    </div>
}
@{
    Vistoria.Business.SessionHelper.ListMessage.Clear();
}

<div id="result"></div>

<div id="form-login">

    @using (Html.BeginForm("Login", "Seguranca", FormMethod.Post, new { @id = "formId", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

        <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
        <div class="form-group has-feedback">
            <div>
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control", placeholder = "Login", autofocus = "on" } })
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group has-feedback">
            <div>
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", placeholder = "Senha", autofocus = "on" } })
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
            </div>
        </div>

        <div class="row mrg-top-15 text-right">
            <a class="text-right" href="javascript:void(0)" onclick="showReset();">Esqueci minha senha</a>
        </div>
    }
</div>

<div class="form-horizontal" id="form-reset" style="display: none;">

    <div class="form-group has-feedback">
        <div>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "E-mail", autofocus = "on" } })
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            <div id="Email-error" class="help-block animation-slideDown" style="display: none;">Informe o E-mail</div>
        </div>
    </div>

    <div class="row">
        <div class="">
            <button type="submit" class="btn btn-primary btn-block btn-flat" id="btnEnviar">Enviar</button>
            <a type="button" class="btn btn-default btn-block btn-flat" href="javascript:void(0)" onclick="hideReset();">Voltar</a>
        </div>
    </div>
   
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Esqueci minha senha</h4>
            </div>
            <div class="modal-body">
                <p id="txtRetorno"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#formId').validate({
                errorClass: 'help-block animation-slideDown',
                errorElement: 'div',
                errorPlacement: function (error, e) {
                    e.parents('.form-group > div').append(error);
                },
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    'Login': {
                        required: true
                    },
                    'Senha': {
                        required: true
                    }
                },
                messages: {
                    'Login': 'Informe o Login',
                    'Senha': 'Informe a Senha'
                }
            });

            $("#Email").on('change', function() {
                if($(this).val() == "") {
                    $("#Email-error").show();
                    $("#Email").parent().addClass("has-error");
                } else {
                    $("#Email-error").hide();
                    $("#Email").parent().removeClass("has-error");
                }
            });

            $('#btnEnviar').click(function () {
                if ($("#Email").val() == "") {
                    $("#Email-error").show();
                    $("#Email").parent().addClass("has-error");
                } else {
                    var obj = new Object();
                    obj.Email = $("#Email").val();

                    $.ajax({
                        method: "POST",
                        dataType: "json",
                        url: '@Url.Action("ResetarSenha", "api/UsuarioApi")',
                        data: obj,
                    }).done(function (result) {
                        if (result.Status == 1) {
                            $("#Email").val("");
                            hideReset();
                        }
                        $("#txtRetorno").html(result.Mensagem);
                        $("#modal-default").modal("show");
                    }).fail(function (jqXHR, textStatus) {
                        alert("Request failed: " + textStatus);
                    });
                }
                
            });

        });

        function showReset() {
            $("#form-login").hide();
            $("#form-reset").show();
            $(".login-box-msg").html("Informe o e-mail cadastrado");
        }

        function hideReset() {
            $("#form-login").show();
            $("#form-reset").hide();
            $(".login-box-msg").html("Entre para iniciar sua sessão");
        }
    </script>
}